Refactor/rename test functions
arcadia-finance/arcadia-vaults pull request #134
Opened 2022-09-22 07:29 UTC by alikonuk1

2022-09-22 08:32 UTC, Thomas-Smets commented on src/test/10_EndToEnd.t.sol
> +    function testSuccess_AmountOfAllowedCredit(uint128 amountEth) public {
Change to: testSuccess_getFreeMargin_AmountOfAllowedCredit

2022-09-22 08:33 UTC, Thomas-Smets commented on src/test/10_EndToEnd.t.sol
> +    function testSuccess_IncreaseOfDebtPerBlock(uint128 amountEth, uint128 amountCredit, uint32 amountOfBlocksToRoll) public {
Change to: testSuccess_borrow_IncreaseOfDebtPerBlock

2022-09-22 08:34 UTC, Thomas-Smets commented on src/test/10_EndToEnd.t.sol
> +    function testRevert_withdraw_IfOpenDebtIsTooLarge(uint128 amountEth, uint128 amountEthWithdrawal) public {
detail, but you can drop the If

2022-09-22 08:34 UTC, Thomas-Smets commented on src/test/10_EndToEnd.t.sol
> +    function testSuccess_withdraw_IfOpenDebtIsNotTooLarge(
detail, but you can drop the If

2022-09-22 08:35 UTC, Thomas-Smets commented on src/test/10_EndToEnd.t.sol
> +    function testSuccess_IncreaseBalanceDebtContractSyncDebt(uint128 amountEth, uint128 amountCredit, uint16 blocksToRoll)
Change to: testSuccess_syncInterests_IncreaseBalanceDebtContract

2022-09-22 08:37 UTC, Thomas-Smets commented on src/test/13_ProxyUpgrade.t.sol
> +    function testSuccess_NewVaultVersion(uint256 salt) public {
Change to: testSuccess_confirmNewVaultInfo_NewVaultLogic

2022-09-22 08:40 UTC, Thomas-Smets commented on src/test/13_ProxyUpgrade.t.sol
> +    function testSuccess_AssetsAfterUpgrade(uint128 amount) public {
testSuccess_confirmNewVaultInfo_StorageVariablesAfterUpgradeAreIdentical

2022-09-22 08:44 UTC, Thomas-Smets commented on src/test/13_ProxyUpgrade.t.sol
> +    function testRevert_upgradeVaultVersion_AssetsAfterUpgradeFail(uint128 amount) public {
testRevert_upgradeVaultVersion_IncompatibleVersionWithCurrentVault

2022-09-22 08:45 UTC, Thomas-Smets commented on src/test/14_ATokenPricingModule.t.sol
> +    function testSuccess_isWhiteListed() public {
testSuccess_setAssetInformation

2022-09-22 08:47 UTC, Thomas-Smets commented on src/test/14_ATokenPricingModule.t.sol
> +    function testSuccess_setAssetInformation_ReturnUsdValueWhenBaseCurrencyIsUsd(uint128 amountEth) public {
testSuccess_getValue_ReturnUsdValueWhenBaseCurrencyIsUsd

2022-09-22 08:49 UTC, Thomas-Smets commented on src/test/1_OracleHub.t.sol
> +    function testSuccess_getRate_WhenBaseCurrencyIsUsdForSingleOracle(
detail (also for the underlying test) drop the When

2022-09-22 09:00 UTC, Thomas-Smets commented on src/test/4_FloorERC721PricingModule.t.sol
> +    function testRevert_AssetInformation_NonOwnerAddsAsset(address unprivilegedAddress) public {
testRevert_setAssetInformation_NonOwnerAddsAsset

Also for next functions don't forget the set

2022-09-22 09:03 UTC, Thomas-Smets commented on src/test/7_Factory.t.sol
> +        /////Make sure vault itsZZZZZZ``````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````ZZZ
No clue what this is, but think we can remove all random characters :D
guess:
//Make sure vault itself is owned by sender

2022-09-22 09:05 UTC, Thomas-Smets commented on src/test/7_Factory.t.sol
>      //Test confirmNewVaultInfo
We can now remove these comments since the function is in the test name itself

2022-09-22 09:09 UTC, Thomas-Smets commented on src/test/8_Vault.t.sol
> +    function testSuccess_borrow(uint8 baseAmountDeposit, uint8 baseAmountCredit) public {
testSuccess_increaseMarginPosition
This test has to be improved in a next task

2022-09-22 09:11 UTC, Thomas-Smets commented on src/test/8_Vault.t.sol
> +    function testSuccess_liquidate_LiquidateVaultFactory(address liquidationKeeper) public {
testSuccess_liquidate

2022-09-22 11:34 UTC, zekiblue requested changes

2022-09-22 11:34 UTC, zekiblue commented on src/test/1_OracleHub.t.sol
> +    function testRevert_getRate_WhenBaseCurrencyIsNotUsdOverflow1(
testRevert_getRate_BaseCurrencyNotUsd_Overflow
is better naming
in general filler words like 'should' 'when' are not that necessary in test naming.
general convention for test naming is [unit_of_work][scenario][expected_result], in our case we should always start with test... to the test naming. It is good to use testRevert or testSuccess. but also good to add expected_result at the end of the test name.

2022-09-22 11:38 UTC, zekiblue requested changes

2022-09-22 11:38 UTC, zekiblue commented on src/test/8_Vault.t.sol
> +    function testSuccess_liquidate_LiquidateVaultFactory(address liquidationKeeper) public {
testSuccess_liquidate_UnhealthyVault_NewOwnerLiquidator

2022-09-22 11:38 UTC, zekiblue commented on src/test/9_Liquidator.t.sol
> +    function testRevert_transferOwnership_ByNonOwner(address from) public {
testRevert_transferOwnership_NonOwner_CallerNotOwner

2022-09-23 09:26 UTC, Thomas-Smets approved these changes
Lgtm

2022-09-23 11:42 UTC, j-vp approved these changes
gtg

2022-09-23 12:51 UTC, merged